kind: pipeline
type: docker
name: Build-PR

steps:
  - name: build
    image: openjdk:8-jdk
    commands:
      - ./gradlew build
  - name: publish
    image: plugins/docker
    settings:
      auto_tag: true
      repo: muhtarh/test-spring
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
      - tag
      - push
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
    - tag

---
kind: pipeline
name: Notification

clone:
  disable: true

steps:
  - name: notify
    image: appleboy/drone-telegram
    message: >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job.
        {{else}}
          build {{build.number}} failed. Fix me please.
        {{/success}}
    settings:
      token:
        from_secret: telegram_token
      to: muhtarh
depends_on:
  - Build-PR

trigger:
  status:
    - success
    - failure
