kind: pipeline
type: docker
name: Build-PR

steps:
  - name: build
    image: openjdk:8-jdk
    commands:
      - ./gradlew clean build
  - name: publish
    image: plugins/docker
    settings:
      auto_tag: true
      repo: muhtarh/test-spring
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tag:
        - latest
    when:
      event:
      - tag
      - push
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
    - tag

---
kind: pipeline
name: Deploy

steps:
  - name: deploy-docker
    image: appleboy/drone-ssh
    settings:
      host: hello.imuttar.com
      username:
        from_secret: ssh_user
      password:
        from_secret: ssh_password
      port: 22
      script:
        - docker-compose down
        - docker-compose up -d
depends_on:
  - Build-PR
trigger:
  branch:
    - master
  event:
    - tag
    - push
---
kind: pipeline
name: Notification

clone:
  disable: true

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: nofitication
      template: >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job.
        {{else}}
          build {{build.number}} failed. Fix me please.
        {{/success}}
depends_on:
  - Build-PR
  - Deploy

trigger:
  status:
    - success
    - failure
