kind: pipeline
type: docker
name: Build PR

steps:
  - name: build-1
    image: openjdk:8-jdk
    commands:
      - ./gradlew build
  - name: build-2
    image: openjdk:8-jdk
    commands:
      - ./gradlew build
  - name: publish
    image: plugins/docker
    settings:
      auto_tag: true
      repo: muhtarh/test-spring
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    depends_on:
      - build-1
      - build-2
    when:
      event:
        - tag
        - push
trigger:
  branch:
  - master
  event:
  - pull_request
  - push
  - tag

---
kind: pipeline
name: Notification

clone:
  disable: true

steps:
  - name: notify
    image: appleboy/drone-telegram
    message: "{{#success build.status}} ✅  Build #{{build.number}} of `{{repo.name}}` succeeded.\n\n📝 Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n\n🌐 {{ build.link }} {{else}} ❌  Build #{{build.number}} of `{{repo.name}}` failed.\n\n📝 Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n\n🌐 {{ build.link }} {{/success}}\n"
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_notify_to
depends_on:
  - build
trigger:
  status:
    - success
    - failure