kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: openjdk:8-jdk
    commands:
      - ./gradlew build
  - name: publish
    image: plugins/docker
    settings:
      auto_tag: true
      repo: drone/drone
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - tag
        - push
trigger:
  branch:
  - master
  event:
  - pull_request
  - push
  - tag
