kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: openjdk:8-jdk
    commands:
      - ./gradlew build
  - name: publish
    image: plugins/docker
    settings:
      auto_tag: true
      repo: muhtarh/test-spring
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - tag
        - push
trigger:
  branch:
  - master
  event:
  - pull_request
  - push
  - tag

---
kind: pipeline
name: notify

clone:
  disable: true

steps:
  - name: notify
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_notify_to
      message_file: message_file.tpl
depends_on:
  - build
trigger:
  status:
    - success
    - failure